### ISSUE TITLE
Enable Massa Station to change networks easily

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station#806]
**Context**
Enable Massa Station to change network easily so that users can switch from Mainnet to Buildnet.

**User flow**

<img width="1142" alt="image" src="https://github.com/massalabs/station/assets/109611779/4e026758-4fe2-4073-9267-d84b0020dfa5">

implement above design: 

- Use the account selection drop down to show the list of networks

**How to**

- [ ] Get the list of networks from the flag `--node-server` 
- [ ] Retrieve this list using and hide all network except: is it possible to hide some networks? 
* For the mainnet, we'll probably want to show only some of them (not 100% sure need to validate this info)
- [ ] Surface the front-end using existing component only: show this info on all massa station pages (same info on all pages of course)
- [ ] Connect to network and display related info

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by SlnPons** [comment]
@Thykof check out the design / component we want to re-use to enable this feature. 
Do you think the "how to" part is clear enough to address it soon?

@gregLibert do you think we should KISS and display all available networks (labnet, testnet, buildnet...) or only buildnet and then mainnet when available?

**Comment by Thykof** [comment]
>  Retrieve this list using and hide all network except: is it possible to hide some networks?

I don' understand this part. You want to hide the networks that massastation is not compatible with?

**Comment by Thykof** [comment]
> @Thykof check out the design / component we want to re-use to enable this feature.

We will use component dropdown, the same use to switch account in the wallet.

**Comment by gregLibert** [comment]
> @gregLibert do you think we should KISS and display all available networks (labnet, testnet, buildnet...) or only buildnet and then mainnet when available?

I'm not sure it will bring a lot of complexity to filter the networks, but I think that Massa Station should by default only know buildnet and testnet. Labnet and co should be defined in the local configuration of Massa Station (back) if needed.

For this to work, we should simply define on the back side a configuration file such as:
```yaml
network:
  testnet:
    - https://test.massa.net/api/v2
  buildnet:
    - https://buildnet.massa.net/api/v2
  labnet:
    - 192.168.2.1
    - 192.168.2.2
  mynet:
    - 127.0.0.1
```

And it that case, Massa Station will have 4 networks. If there is no such configuration, only testnet and buildnet should exist with the default value given here.

**Comment by SlnPons** [comment]
Yes, agreed with @gregLibert. Only Testnet and buildnet should be listed into Massa Station front-end for now. 
cc @Thykof hope that with this answer you understand my original question ;) 

@B-Naoufal fyi. Does it make sense to you and do you have a clear action plan in mind (please share in comment ;) ) to tackle this please?

**Comment by gregLibert** [comment]
My remarks:
- `Get the list of networks from the flag --node-server` => I disagree. I think that we should use a configuration file instead because as explained in my comment above, we could have a complex configuration
- `add a new endpoint to update the nodeURL /config/node-url, operationID : updateNodeURL` same as above, we are not tlaking about a node or a node URL, we are tlaking about a network configuration that can have multiple nodes.
- `modify the api.NewServer function to use a global and not local variable config.AppConfig` using global variable is a bad practice. You should use a package to handle that cleanly; be careful with the concurrency.

**Comment by Thykof** [comment]
We should not forget about DNS address, I would suggest this configuration file:

```yaml
network:
  testnet:
    dns: AS...
    urls:
      - https://test.massa.net/api/v2
  buildnet:
    dns: AS...
    urls:
      - https://buildnet.massa.net/api/v2
  labnet:
    dns: AS...
    urls:
      - 192.168.2.1
      - 192.168.2.2
  mynet:
    dns: AS...
    urls:
      - 127.0.0.1
```
